# Generated by Django 4.1.1 on 2022-09-15 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('indicators', '0002_alter_indicator_symbol'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=255)),
                ('reportedCurrency', models.CharField(max_length=255)),
                ('cik', models.CharField(max_length=255)),
                ('fillingDate', models.DateField(max_length=255)),
                ('acceptedDate', models.DateField(max_length=255)),
                ('calendarYear', models.IntegerField(max_length=255)),
                ('period', models.CharField(max_length=255)),
                ('revenue', models.IntegerField()),
                ('costOfRevenue', models.IntegerField()),
                ('grossProfit', models.IntegerField()),
                ('grossProfitRatio', models.FloatField()),
                ('researchAndDevelopmentExpenses', models.IntegerField()),
                ('generalAndAdministrativeExpenses', models.FloatField()),
                ('sellingAndMarketingExpenses', models.FloatField()),
                ('sellingGeneralAndAdministrativeExpenses', models.IntegerField()),
                ('otherExpenses', models.FloatField()),
                ('operatingExpenses', models.IntegerField()),
                ('costAndExpenses', models.IntegerField()),
                ('interestIncome', models.IntegerField()),
                ('interestExpense', models.IntegerField()),
                ('depreciationAndAmortization', models.IntegerField()),
                ('ebitda', models.IntegerField()),
                ('ebitdaratio', models.FloatField()),
                ('operatingIncome', models.IntegerField()),
                ('operatingIncomeRatio', models.FloatField()),
                ('totalOtherIncomeExpensesNet', models.IntegerField()),
                ('incomeBeforeTax', models.IntegerField()),
                ('incomeBeforeTaxRatio', models.FloatField()),
                ('incomeTaxExpense', models.IntegerField()),
                ('netIncome', models.IntegerField()),
                ('netIncomeRatio', models.FloatField()),
                ('eps', models.FloatField()),
                ('epsdiluted', models.FloatField()),
                ('weightedAverageShsOut', models.IntegerField()),
                ('weightedAverageShsOutDil', models.IntegerField()),
                ('link', models.CharField(max_length=255)),
                ('finalLink', models.CharField(max_length=255)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicators.indicator')),
            ],
        ),
    ]
