# Generated by Django 4.1.1 on 2022-09-15 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annual_reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomestatement',
            name='calendarYear',
            field=models.IntegerField(),
        ),
    ]
