# Generated by Django 4.1.1 on 2022-09-15 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0002_alter_indicator_symbol'),
        ('annual_reports', '0002_alter_incomestatement_calendaryear'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceSheetStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reportedCurrency', models.CharField(max_length=255)),
                ('cik', models.CharField(max_length=255)),
                ('fillingDate', models.DateField()),
                ('acceptedDate', models.DateField()),
                ('calendarYear', models.IntegerField()),
                ('period', models.CharField(max_length=255)),
                ('cashAndCashEquivalents', models.IntegerField()),
                ('shortTermInvestments', models.IntegerField()),
                ('cashAndShortTermInvestments', models.IntegerField()),
                ('netReceivables', models.IntegerField()),
                ('inventory', models.IntegerField()),
                ('otherCurrentAssets', models.IntegerField()),
                ('totalCurrentAssets', models.IntegerField()),
                ('propertyPlantEquipmentNet', models.IntegerField()),
                ('goodwill', models.FloatField()),
                ('intangibleAssets', models.FloatField()),
                ('goodwillAndIntangibleAssets', models.FloatField()),
                ('longTermInvestments', models.IntegerField()),
                ('taxAssets', models.FloatField()),
                ('otherNonCurrentAssets', models.IntegerField()),
                ('totalNonCurrentAssets', models.IntegerField()),
                ('otherAssets', models.FloatField()),
                ('totalAssets', models.IntegerField()),
                ('accountPayables', models.IntegerField()),
                ('shortTermDebt', models.IntegerField()),
                ('taxPayables', models.FloatField()),
                ('deferredRevenue', models.IntegerField()),
                ('otherCurrentLiabilities', models.IntegerField()),
                ('totalCurrentLiabilities', models.IntegerField()),
                ('longTermDebt', models.IntegerField()),
                ('deferredRevenueNonCurrent', models.FloatField()),
                ('deferredTaxLiabilitiesNonCurrent', models.FloatField()),
                ('otherNonCurrentLiabilities', models.IntegerField()),
                ('totalNonCurrentLiabilities', models.IntegerField()),
                ('otherLiabilities', models.FloatField()),
                ('capitalLeaseObligations', models.FloatField()),
                ('totalLiabilities', models.IntegerField()),
                ('preferredStock', models.FloatField()),
                ('commonStock', models.IntegerField()),
                ('retainedEarnings', models.IntegerField()),
                ('accumulatedOtherComprehensiveIncomeLoss', models.IntegerField()),
                ('othertotalStockholdersEquity', models.FloatField()),
                ('totalStockholdersEquity', models.IntegerField()),
                ('totalLiabilitiesAndStockholdersEquity', models.IntegerField()),
                ('minorityInterest', models.IntegerField()),
                ('totalEquity', models.IntegerField()),
                ('totalLiabilitiesAndTotalEquity', models.IntegerField()),
                ('totalInvestments', models.IntegerField()),
                ('totalDebt', models.IntegerField()),
                ('netDebt', models.IntegerField()),
                ('link', models.CharField(max_length=255)),
                ('finalLink', models.CharField(max_length=255)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicators.indicator')),
            ],
        ),
    ]
