# Generated by Django 4.1.1 on 2022-09-16 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0002_alter_indicator_symbol'),
        ('annual_reports', '0003_balancesheetstatement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancesheetstatement',
            name='accountPayables',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='balancesheetstatement',
            name='accumulatedOtherComprehensiveIncomeLoss',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='balancesheetstatement',
            name='calendarYear',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='balancesheetstatement',
            name='cashAndCashEquivalents',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='balancesheetstatement',
            name='cashAndShortTermInvestments',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='balancesheetstatement',
            name='commonStock',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='balancesheetstatement',
            name='deferredRevenue',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='balancesheetstatement',
            name='inventory',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='balancesheetstatement',
            name='longTermDebt',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='balancesheetstatement',
            name='longTermInvestments',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='balancesheetstatement',
            name='minorityInterest',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='balancesheetstatement',
            name='netDebt',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='balancesheetstatement',
            name='netReceivables',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='balancesheetstatement',
            name='otherCurrentAssets',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='balancesheetstatement',
            name='otherCurrentLiabilities',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='balancesheetstatement',
            name='otherNonCurrentAssets',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='balancesheetstatement',
            name='otherNonCurrentLiabilities',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='balancesheetstatement',
            name='propertyPlantEquipmentNet',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='balancesheetstatement',
            name='retainedEarnings',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='balancesheetstatement',
            name='shortTermDebt',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='balancesheetstatement',
            name='shortTermInvestments',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='balancesheetstatement',
            name='totalAssets',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='balancesheetstatement',
            name='totalCurrentAssets',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='balancesheetstatement',
            name='totalCurrentLiabilities',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='balancesheetstatement',
            name='totalDebt',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='balancesheetstatement',
            name='totalEquity',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='balancesheetstatement',
            name='totalInvestments',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='balancesheetstatement',
            name='totalLiabilities',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='balancesheetstatement',
            name='totalLiabilitiesAndStockholdersEquity',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='balancesheetstatement',
            name='totalLiabilitiesAndTotalEquity',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='balancesheetstatement',
            name='totalNonCurrentAssets',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='balancesheetstatement',
            name='totalNonCurrentLiabilities',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='balancesheetstatement',
            name='totalStockholdersEquity',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='incomestatement',
            name='calendarYear',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='incomestatement',
            name='costAndExpenses',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='incomestatement',
            name='costOfRevenue',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='incomestatement',
            name='depreciationAndAmortization',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='incomestatement',
            name='ebitda',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='incomestatement',
            name='grossProfit',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='incomestatement',
            name='incomeBeforeTax',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='incomestatement',
            name='incomeTaxExpense',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='incomestatement',
            name='interestExpense',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='incomestatement',
            name='interestIncome',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='incomestatement',
            name='netIncome',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='incomestatement',
            name='operatingExpenses',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='incomestatement',
            name='operatingIncome',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='incomestatement',
            name='researchAndDevelopmentExpenses',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='incomestatement',
            name='revenue',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='incomestatement',
            name='sellingGeneralAndAdministrativeExpenses',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='incomestatement',
            name='totalOtherIncomeExpensesNet',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='incomestatement',
            name='weightedAverageShsOut',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='incomestatement',
            name='weightedAverageShsOutDil',
            field=models.BigIntegerField(),
        ),
        migrations.CreateModel(
            name='CashFlowStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reportedCurrency', models.CharField(max_length=255)),
                ('cik', models.CharField(max_length=255)),
                ('fillingDate', models.DateField()),
                ('acceptedDate', models.DateField()),
                ('calendarYear', models.BigIntegerField()),
                ('period', models.CharField(max_length=255)),
                ('netIncome', models.BigIntegerField()),
                ('depreciationAndAmortization', models.BigIntegerField()),
                ('deferredIncomeTax', models.BigIntegerField()),
                ('stockBasedCompensation', models.BigIntegerField()),
                ('changeInWorkingCapital', models.BigIntegerField()),
                ('accountsReceivables', models.BigIntegerField()),
                ('inventory', models.BigIntegerField()),
                ('accountsPayables', models.BigIntegerField()),
                ('otherWorkingCapital', models.BigIntegerField()),
                ('otherNonCashItems', models.BigIntegerField()),
                ('netCashProvidedByOperatingActivities', models.BigIntegerField()),
                ('investmentsInPropertyPlantAndEquipment', models.BigIntegerField()),
                ('acquisitionsNet', models.BigIntegerField()),
                ('purchasesOfInvestments', models.BigIntegerField()),
                ('salesMaturitiesOfInvestments', models.BigIntegerField()),
                ('otherInvestingActivites', models.BigIntegerField()),
                ('netCashUsedForInvestingActivites', models.BigIntegerField()),
                ('debtRepayment', models.BigIntegerField()),
                ('commonStockIssued', models.BigIntegerField()),
                ('commonStockRepurchased', models.BigIntegerField()),
                ('dividendsPaid', models.BigIntegerField()),
                ('otherFinancingActivites', models.BigIntegerField()),
                ('netCashUsedProvidedByFinancingActivities', models.BigIntegerField()),
                ('effectOfForexChangesOnCash', models.FloatField()),
                ('netChangeInCash', models.BigIntegerField()),
                ('cashAtEndOfPeriod', models.BigIntegerField()),
                ('cashAtBeginningOfPeriod', models.BigIntegerField()),
                ('operatingCashFlow', models.BigIntegerField()),
                ('capitalExpenditure', models.BigIntegerField()),
                ('freeCashFlow', models.BigIntegerField()),
                ('link', models.CharField(max_length=255)),
                ('finalLink', models.CharField(max_length=255)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicators.indicator')),
            ],
        ),
    ]
