from django.db import models

from indicators.models import Indicator


class IncomeStatement(models.Model):
    date = models.DateField(max_length=255)
    symbol = models.ForeignKey(Indicator, on_delete=models.CASCADE)
    reportedCurrency = models.CharField(max_length=255)
    cik = models.CharField(max_length=255)
    fillingDate = models.DateField(max_length=255)
    acceptedDate = models.DateField(max_length=255)
    calendarYear = models.IntegerField()
    period = models.CharField(max_length=255)
    revenue = models.IntegerField()
    costOfRevenue = models.IntegerField()
    grossProfit = models.IntegerField()
    grossProfitRatio = models.FloatField()
    researchAndDevelopmentExpenses = models.IntegerField()
    generalAndAdministrativeExpenses = models.FloatField()
    sellingAndMarketingExpenses = models.FloatField()
    sellingGeneralAndAdministrativeExpenses = models.IntegerField()
    otherExpenses = models.FloatField()
    operatingExpenses = models.IntegerField()
    costAndExpenses = models.IntegerField()
    interestIncome = models.IntegerField()
    interestExpense = models.IntegerField()
    depreciationAndAmortization = models.IntegerField()
    ebitda = models.IntegerField()
    ebitdaratio = models.FloatField()
    operatingIncome = models.IntegerField()
    operatingIncomeRatio = models.FloatField()
    totalOtherIncomeExpensesNet = models.IntegerField()
    incomeBeforeTax = models.IntegerField()
    incomeBeforeTaxRatio = models.FloatField()
    incomeTaxExpense = models.IntegerField()
    netIncome = models.IntegerField()
    netIncomeRatio = models.FloatField()
    eps = models.FloatField()
    epsdiluted = models.FloatField()
    weightedAverageShsOut = models.IntegerField()
    weightedAverageShsOutDil = models.IntegerField()
    link = models.CharField(max_length=255)
    finalLink = models.CharField(max_length=255)


class BalanceSheetStatement(models.Model):
    date = models.DateField()
    symbol = models.ForeignKey(Indicator, on_delete=models.CASCADE)
    reportedCurrency = models.CharField(max_length=255)
    cik = models.CharField(max_length=255)
    fillingDate = models.DateField()
    acceptedDate = models.DateField()
    calendarYear = models.IntegerField()
    period = models.CharField(max_length=255)
    cashAndCashEquivalents = models.IntegerField()
    shortTermInvestments = models.IntegerField()
    cashAndShortTermInvestments = models.IntegerField()
    netReceivables = models.IntegerField()
    inventory = models.IntegerField()
    otherCurrentAssets = models.IntegerField()
    totalCurrentAssets = models.IntegerField()
    propertyPlantEquipmentNet = models.IntegerField()
    goodwill = models.FloatField()
    intangibleAssets = models.FloatField()
    goodwillAndIntangibleAssets = models.FloatField()
    longTermInvestments = models.IntegerField()
    taxAssets = models.FloatField()
    otherNonCurrentAssets = models.IntegerField()
    totalNonCurrentAssets = models.IntegerField()
    otherAssets = models.FloatField()
    totalAssets = models.IntegerField()
    accountPayables = models.IntegerField()
    shortTermDebt = models.IntegerField()
    taxPayables = models.FloatField()
    deferredRevenue = models.IntegerField()
    otherCurrentLiabilities = models.IntegerField()
    totalCurrentLiabilities = models.IntegerField()
    longTermDebt = models.IntegerField()
    deferredRevenueNonCurrent = models.FloatField()
    deferredTaxLiabilitiesNonCurrent = models.FloatField()
    otherNonCurrentLiabilities = models.IntegerField()
    totalNonCurrentLiabilities = models.IntegerField()
    otherLiabilities = models.FloatField()
    capitalLeaseObligations = models.FloatField()
    totalLiabilities = models.IntegerField()
    preferredStock = models.FloatField()
    commonStock = models.IntegerField()
    retainedEarnings = models.IntegerField()
    accumulatedOtherComprehensiveIncomeLoss = models.IntegerField()
    othertotalStockholdersEquity = models.FloatField()
    totalStockholdersEquity = models.IntegerField()
    totalLiabilitiesAndStockholdersEquity = models.IntegerField()
    minorityInterest = models.IntegerField()
    totalEquity = models.IntegerField()
    totalLiabilitiesAndTotalEquity = models.IntegerField()
    totalInvestments = models.IntegerField()
    totalDebt = models.IntegerField()
    netDebt = models.IntegerField()
    link = models.CharField(max_length=255)
    finalLink = models.CharField(max_length=255)
