from django.db import models

from indicators.models import Indicator


class IncomeStatement(models.Model):
    date = models.DateField(max_length=255)
    symbol = models.ForeignKey(Indicator, on_delete=models.CASCADE)
    reportedCurrency = models.CharField(max_length=255)
    cik = models.CharField(max_length=255)
    fillingDate = models.DateField(max_length=255)
    acceptedDate = models.DateField(max_length=255)
    calendarYear = models.IntegerField()
    period = models.CharField(max_length=255)
    revenue = models.IntegerField()
    costOfRevenue = models.IntegerField()
    grossProfit = models.IntegerField()
    grossProfitRatio = models.FloatField()
    researchAndDevelopmentExpenses = models.IntegerField()
    generalAndAdministrativeExpenses = models.FloatField()
    sellingAndMarketingExpenses = models.FloatField()
    sellingGeneralAndAdministrativeExpenses = models.IntegerField()
    otherExpenses = models.FloatField()
    operatingExpenses = models.IntegerField()
    costAndExpenses = models.IntegerField()
    interestIncome = models.IntegerField()
    interestExpense = models.IntegerField()
    depreciationAndAmortization = models.IntegerField()
    ebitda = models.IntegerField()
    ebitdaratio = models.FloatField()
    operatingIncome = models.IntegerField()
    operatingIncomeRatio = models.FloatField()
    totalOtherIncomeExpensesNet = models.IntegerField()
    incomeBeforeTax = models.IntegerField()
    incomeBeforeTaxRatio = models.FloatField()
    incomeTaxExpense = models.IntegerField()
    netIncome = models.IntegerField()
    netIncomeRatio = models.FloatField()
    eps = models.FloatField()
    epsdiluted = models.FloatField()
    weightedAverageShsOut = models.IntegerField()
    weightedAverageShsOutDil = models.IntegerField()
    link = models.CharField(max_length=255)
    finalLink = models.CharField(max_length=255)
