from django.db import models

from indicators.models import Indicator


class IncomeStatement(models.Model):
    date = models.DateField(max_length=255)
    symbol = models.ForeignKey(Indicator, on_delete=models.CASCADE)
    reportedCurrency = models.CharField(max_length=255)
    cik = models.CharField(max_length=255)
    fillingDate = models.DateField(max_length=255)
    acceptedDate = models.DateField(max_length=255)
    calendarYear = models.BigIntegerField()
    period = models.CharField(max_length=255)
    revenue = models.BigIntegerField()
    costOfRevenue = models.BigIntegerField()
    grossProfit = models.BigIntegerField()
    grossProfitRatio = models.FloatField()
    researchAndDevelopmentExpenses = models.BigIntegerField()
    generalAndAdministrativeExpenses = models.FloatField()
    sellingAndMarketingExpenses = models.FloatField()
    sellingGeneralAndAdministrativeExpenses = models.BigIntegerField()
    otherExpenses = models.FloatField()
    operatingExpenses = models.BigIntegerField()
    costAndExpenses = models.BigIntegerField()
    interestIncome = models.BigIntegerField()
    interestExpense = models.BigIntegerField()
    depreciationAndAmortization = models.BigIntegerField()
    ebitda = models.BigIntegerField()
    ebitdaratio = models.FloatField()
    operatingIncome = models.BigIntegerField()
    operatingIncomeRatio = models.FloatField()
    totalOtherIncomeExpensesNet = models.BigIntegerField()
    incomeBeforeTax = models.BigIntegerField()
    incomeBeforeTaxRatio = models.FloatField()
    incomeTaxExpense = models.BigIntegerField()
    netIncome = models.BigIntegerField()
    netIncomeRatio = models.FloatField()
    eps = models.FloatField()
    epsdiluted = models.FloatField()
    weightedAverageShsOut = models.BigIntegerField()
    weightedAverageShsOutDil = models.BigIntegerField()
    link = models.CharField(max_length=255)
    finalLink = models.CharField(max_length=255)


class BalanceSheetStatement(models.Model):
    date = models.DateField()
    symbol = models.ForeignKey(Indicator, on_delete=models.CASCADE)
    reportedCurrency = models.CharField(max_length=255)
    cik = models.CharField(max_length=255)
    fillingDate = models.DateField()
    acceptedDate = models.DateField()
    calendarYear = models.BigIntegerField()
    period = models.CharField(max_length=255)
    cashAndCashEquivalents = models.BigIntegerField()
    shortTermInvestments = models.BigIntegerField()
    cashAndShortTermInvestments = models.BigIntegerField()
    netReceivables = models.BigIntegerField()
    inventory = models.BigIntegerField()
    otherCurrentAssets = models.BigIntegerField()
    totalCurrentAssets = models.BigIntegerField()
    propertyPlantEquipmentNet = models.BigIntegerField()
    goodwill = models.FloatField()
    intangibleAssets = models.FloatField()
    goodwillAndIntangibleAssets = models.FloatField()
    longTermInvestments = models.BigIntegerField()
    taxAssets = models.FloatField()
    otherNonCurrentAssets = models.BigIntegerField()
    totalNonCurrentAssets = models.BigIntegerField()
    otherAssets = models.FloatField()
    totalAssets = models.BigIntegerField()
    accountPayables = models.BigIntegerField()
    shortTermDebt = models.BigIntegerField()
    taxPayables = models.FloatField()
    deferredRevenue = models.BigIntegerField()
    otherCurrentLiabilities = models.BigIntegerField()
    totalCurrentLiabilities = models.BigIntegerField()
    longTermDebt = models.BigIntegerField()
    deferredRevenueNonCurrent = models.FloatField()
    deferredTaxLiabilitiesNonCurrent = models.FloatField()
    otherNonCurrentLiabilities = models.BigIntegerField()
    totalNonCurrentLiabilities = models.BigIntegerField()
    otherLiabilities = models.FloatField()
    capitalLeaseObligations = models.FloatField()
    totalLiabilities = models.BigIntegerField()
    preferredStock = models.FloatField()
    commonStock = models.BigIntegerField()
    retainedEarnings = models.BigIntegerField()
    accumulatedOtherComprehensiveIncomeLoss = models.BigIntegerField()
    othertotalStockholdersEquity = models.FloatField()
    totalStockholdersEquity = models.BigIntegerField()
    totalLiabilitiesAndStockholdersEquity = models.BigIntegerField()
    minorityInterest = models.BigIntegerField()
    totalEquity = models.BigIntegerField()
    totalLiabilitiesAndTotalEquity = models.BigIntegerField()
    totalInvestments = models.BigIntegerField()
    totalDebt = models.BigIntegerField()
    netDebt = models.BigIntegerField()
    link = models.CharField(max_length=255)
    finalLink = models.CharField(max_length=255)


class CashFlowStatement(models.Model):
    date = models.DateField()
    symbol = models.ForeignKey(Indicator, on_delete=models.CASCADE)
    reportedCurrency = models.CharField(max_length=255)
    cik = models.CharField(max_length=255)
    fillingDate = models.DateField()
    acceptedDate = models.DateField()
    calendarYear = models.BigIntegerField()
    period = models.CharField(max_length=255)
    netIncome = models.BigIntegerField()
    depreciationAndAmortization = models.BigIntegerField()
    deferredIncomeTax = models.BigIntegerField()
    stockBasedCompensation = models.BigIntegerField()
    changeInWorkingCapital = models.BigIntegerField()
    accountsReceivables = models.BigIntegerField()
    inventory = models.BigIntegerField()
    accountsPayables = models.BigIntegerField()
    otherWorkingCapital = models.BigIntegerField()
    otherNonCashItems = models.BigIntegerField()
    netCashProvidedByOperatingActivities = models.BigIntegerField()
    investmentsInPropertyPlantAndEquipment = models.BigIntegerField()
    acquisitionsNet = models.BigIntegerField()
    purchasesOfInvestments = models.BigIntegerField()
    salesMaturitiesOfInvestments = models.BigIntegerField()
    otherInvestingActivites = models.BigIntegerField()
    netCashUsedForInvestingActivites = models.BigIntegerField()
    debtRepayment = models.BigIntegerField()
    commonStockIssued = models.BigIntegerField()
    commonStockRepurchased = models.BigIntegerField()
    dividendsPaid = models.BigIntegerField()
    otherFinancingActivites = models.BigIntegerField()
    netCashUsedProvidedByFinancingActivities = models.BigIntegerField()
    effectOfForexChangesOnCash = models.FloatField()
    netChangeInCash = models.BigIntegerField()
    cashAtEndOfPeriod = models.BigIntegerField()
    cashAtBeginningOfPeriod = models.BigIntegerField()
    operatingCashFlow = models.BigIntegerField()
    capitalExpenditure = models.BigIntegerField()
    freeCashFlow = models.BigIntegerField()
    link = models.CharField(max_length=255)
    finalLink = models.CharField(max_length=255)
