version: '3.5'

services:
  web:
    build: .
    ports:
      - '8080:8080'
    entrypoint: 'bash -c "python manage.py runserver 0.0.0.0:8080"'
    env_file:
      - .env
    volumes:
      - ./:/code
  db:
    image: postgres
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
